# Generated by Django 3.2.19 on 2023-07-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20230722_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ratings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item_to_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.item'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ph_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
