# Generated by Django 3.2.19 on 2023-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20230722_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
