# Generated by Django 3.2.19 on 2023-07-22 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_cart_instamojo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
