# Generated by Django 3.2.19 on 2023-07-22 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
