# Generated by Django 3.2.19 on 2023-07-23 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('Code', models.CharField(max_length=10, unique=True)),
                ('discount', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
