# Generated by Django 3.2.19 on 2023-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('P', 'percentage'), ('A', 'amount'), ('N', 'none')], default='N', max_length=1),
        ),
    ]
